monitor = ,preferred,auto,1

env = XDG_SESSION_TYPE,wayland
env = QT_QPA_PLATFORM,wayland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

misc {
	disable_hyprland_logo = true
	disable_splash_rendering = true
}

exec = sh -lc 'qs -c zshell-greeter; hyprctl dispatch exit'
