name: Lint (QML)

on:
  pull_request:

jobs:
  lint:
    runs-on: debian
    container: debian:sid

    steps:
      - name: Install tools
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            git \
            nodejs \
            npm \
            qt6-declarative-dev-tools

      - name: Checkout
        uses: actions/checkout@v4

      - name: QML lint
        run: |
          if command -v qmllint >/dev/null 2>&1; then
            if [ -n "$(find . -name "*.qml" -print -quit)" ]; then
              find . -name "*.qml" -print0 | xargs -0 qmllint
            else
              echo "No QML files found"
            fi
          else
            echo "No qmllint in PATH"
          fi
