[package]
name = "zshell-img-tools"
version = "0.2.0"
edition = "2024"

[[bin]]
name = "zshell-img-tools"
path = "src/main.rs"

[dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
tiny-skia = { version = "0.11", default-features = false, features = ["std", "simd"] }
serde = { version = "1", features = ["derive"] }
anyhow = "1.0"
serde_json = "1.0.149"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
